include:
  - package:very_good_analysis/analysis_options.yaml
  - package:bloc_lint/recommended.yaml
formatter:
  trailing_commas: preserve
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_catches_without_on_clauses: ignore
    cascade_invocations: ignore
    discarded_futures: ignore
bloc:
  rules:
    prefer_void_public_cubit_methods: false
